source_type: custom_scene
output_type: custom_scene_output

description: Landsat 7 LEDAPS 30 metre, 1deg tile, WGS84 projection (EPSG:4326)

location: '/datacube/ingested_data'
file_path_template: 'LS7_ETM_LEDAPS/Custom_Test/LS7_ETM_LEDAPS_4326_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'
global_attributes:
  title: CEOS Data Cube Landsat Surface Reflectance
  summary: Landsat 7 Enhanced Thematic Mapper Plus Analysis Ready data prepared by NASA on behalf of CEOS.
  source: Surface reflectance from LEDAPS
  institution: CEOS
  instrument: ETM
  cdm_data_type: Grid
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,REFLECTANCE,ETM+,TM,OLI,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: LANDSAT-7
  processing_level: L2
  product_version: '2.0.0'
  product_suite: USGS Landsat
  project: CEOS
  coverage_content_type: physicalMeasurement
  references: http://dx.doi.org/10.3334/ORNLDAAC/1146
  license: https://creativecommons.org/licenses/by/4.0/
  naming_authority: gov.usgs
  acknowledgment: Landsat data is provided by the United States Geological Survey (USGS).

storage:
  driver: NetCDF CF

  crs: EPSG:4326
  tile_size:
          longitude: 0.9479715
          latitude: 0.9494975
  resolution:
          #colombia (1/length of 1 degree in meters there / 30 meters per pixel
          longitude: 0.000270849
          latitude: -0.000271285
  chunking:
      longitude: 500
      latitude: 500
      time: 1
  dimension_order: ['time', 'latitude', 'longitude']

measurements:
    - name: red
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band3'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.63-0.69 microns (Red)"
          alias: "band_3"
    - name: nir
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band4'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.76-0.90 microns (Near Infrared)"
          alias: "band_4"
    - name: swir1
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band5'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 1.55-1.75 microns (Short-wave Infrared)"
          alias: "band_5"
    - name: swir2
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band7'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 2.08-2.35 microns (Short-wave Infrared)"
          alias: "band_7"
